### ISSUE TITLE
keyboard doesn't work

### ISSUE THREAD

**Issue by scuderia666** [Larpon/jni#14]
this is the keyboard example:

11-11 19:57:36.985 18850 18850 W InputMethodManager: Ignoring showSoftInput() as view=android.widget.EditText{20a16a4 VFED..CL. ......ID 0,0-1080,119 aid=1073741842} is not served.

**Comment by scuderia666** [comment]
using "imm.showSoftInput(editText, InputMethodManager.SHOW_IMPLICIT)" instead of "imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0)" at line VKeyboardActivity:113 works somehow.

**Comment by larpon** [comment]
Thanks for the bug report. It used to work so maybe something has changed somewhere in Android-land 🤔

**Comment by scuderia666** [comment]
no problem. also there's this: `error: unknown type 'os.NativeActivity' in android.c.v` when building it as a desktop app. should i create a separate issue?

**Comment by scuderia666** [comment]
I temporarily fixed it by making desktop and android clients as separate modules to avoid importing jni while using desktop client

**Comment by larpon** [comment]
> no problem. also there's this: `error: unknown type 'os.NativeActivity' in android.c.v` when building it as a desktop app. should i create a separate issue?

Thanks. Yes, that would be a big help

**Comment by larpon** [comment]
Right it turns out it has been deprecated/removed from API level 33:
![image](https://github.com/user-attachments/assets/60841933-87d9-4295-a765-bd82b1e6b13c)

**Comment by larpon** [comment]
> using "imm.showSoftInput(editText, InputMethodManager.SHOW_IMPLICIT)" instead of "imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0)" at line VKeyboardActivity:113 works somehow.

Thanks for hinting this. It should work on `master` branch now 👍🏻
